#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "django-fritzconnection"
name = "django-fritzconnection"
description.en = "Web based FritzBox management using Python/Django."

version = "0.2.0~ynh3"

maintainers = ["Jens Diemer"]

[upstream]
license = "GPL-3.0"
code = "https://github.com/jedie/django-fritzconnection"

[integration]
yunohost = ">= 11.2.12"
architectures = "all"
multi_instance = true
ldap = true
sso = true
disk = "100M"
ram.build = "500M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/django-fritzconnection"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = [
        "build-essential",
        "python3-dev",
        "python3-pip",
        "python3-venv",
        "git",
        "libpq-dev",
        "postgresql",
        "postgresql-contrib",
        "redis-server",
    ]

    [resources.database]
    type = "postgresql"
